### ISSUE TITLE
Additional design scenarios for prEN1992 and fib MC2010

### ISSUE THREAD

**Issue by slobbeat** [TNO/shear_calibration#11]
For the two resistance formulas from prEN1992 and fib MC2010 there are two additional parameters to be considered in the design scenarios:
1. D_lower (a parameter related to d_g - the maximum aggregate size -). From Yuguang's email (March 26th 2021) we learned it is typically varying between 8 mm to 24 mm. The maximum aggregate size is typically 8 - 16 - 24 or 32 mm, while you don’t really have sieve size in between. So, D_lower will be discretized with 8, 16, and 24 mm.
2. The shear span to depth ratio (a/d). This we can discretize with the following values: 2.0, 3.0 and 4.0. For cases with a/d < 2.0, shear is often not critical (because of direct force transfer; EC allows to omit the cross-sectional checks, see below). Cases with a/d > 4.0, there will not be much difference anymore.

From a/d, we can also compute the M/V ratios, by assuming M = V x a.

![image](https://user-images.githubusercontent.com/52159490/160413794-bb1a2e13-47c0-4583-b03f-6c16f78f7ef7.png)

**Comment by rozsasarpi** [comment]
Done for MC2010 level II #6 and put on hold for prEN1992 #12 due to surprising `VRmin` values. In light of this I close this issue as solved, if later we decide to resume to prEN1992 that should go to a separate issue.
