### ISSUE TITLE
Missing check in MC2010

### ISSUE THREAD

**Issue by slobbeat** [TNO/shear_calibration#15]
The MC2010 formula requires a check that sqrt(fck) <= 8 MPa. If I'm correct, this is not in the code yet.

**Comment by rozsasarpi** [comment]
I think it is already there in this line (`min(sqrt(fc(ii)), 8)`):
https://github.com/TNO/shear_calibration/blob/3b0f9589ec024a92044dafa1ed3139cec4871028/code/shared_utils/resistance_models/MC2010_level_II_codified_2019.m#L74

**Comment by slobbeat** [comment]
You're right, thanks!
