### ISSUE TITLE
Check on input

### ISSUE THREAD

**Issue by slobbeat** [TNO/shear_calibration#17]
The case:
- The design scenarios are generated from the discretization specified in get_input.m. 
- We have shear formulas with different input parameters, where the a/d and d_dg are only used in fib MC2010.
- If I calibrate EC2 and forgot to set a/d and d_dg to a fixed value, and instead have discretized ranges for them, I will end up with a few times the same design scenarios in DS.p_ds_all (i.e. they differ with respect to a/d and d_dg, but those parameters are not relevant for EC2 shear formula). 
- I don't think it matter for the optimal value, but the calibration is quite inefficient.

Proposed solution(s):
- Add a check in get_input.m if all necessary input parameters for the considered formula are specified and set the others (i.e. not used parameters) to a fixed value (e.g. NaN), or
- Add a filter in gen_DS on unique DS (tricky, because load and resistance are separated).

**Comment by rozsasarpi** [comment]
I agree, I think the first proposal is the easiest to implement, ideally with a warning to notify the user that the variables are dropped. (This could be so nicely implemented in python, where one can programmatically obtain the input arguments of functions, so this check and dropping unnecessary scenarios could be done in a general manner.)
