### ISSUE TITLE
What are the variables in the shear database: `beam_p_adj.mat`?

### ISSUE THREAD

**Issue by rozsasarpi** [TNO/shear_calibration#5]
Although the database will not be added to the code repository, I want to add to it a description of it (at least for our future selves). However, I'm not sure about what certain variables stand for. This is what I have so far:

* `bw`: [mm] smallest width of the cross section in the tensile area
* `d`: [mm] effective depth
* `dg`: [mm]
* `fc`: [MPa] concrete compressive strength
* `mvd`: ?
* `rho`: [%] longitudinal reinforcement ratio
* `vu`: ?
* `Vu`: [kN] so far I used this as the experimentally measured ultimate load (resistance)
* `Vu1`: ?

Could you help me out with the interpretation?

**Comment by rozsasarpi** [comment]
Solved by documenting the interpretation got from @Yuguang-Yang , https://github.com/TNO/shear_calibration/commit/a4a5527d04885528f5e8df14765ca4ce9e857296.

**Comment by slobbeat** [comment]
For the prEN en fib Model code we will add to
