### ISSUE TITLE
Quantification of the impact of resistance model improvements

### ISSUE THREAD

**Issue by rozsasarpi** [TNO/shear_calibration#8]
I'm opening this issue to discuss how we quantify the impact of resistance model improvements and in general how we compare different models. I think the comparison on the level of partial factors is not sufficient and can even be misleading. I suggest to make the comparison on the level of design resistance values obtained from optimized semi-probabilistic formats. For the formulas we consider the design resistances can be considered as proxies of material usage and in turn cost.

For example to have an estimate of what kind of gain we may expect from using MC2010 instead of EN1992, I used the model uncertainty coefficient of variation (cv) of MC2010 (see #6 ) in combination with the rest of the EN1992 model (approximation). Here are the results:

| model | cv of `theta_R` | `C_Rck` | `gamma_C` | `C_Rck / gamma_C` |
| --| -- | -- | -- | -- |
| EN1992 | 0.2376 | 0.1471 | 1.38 | 0.107 |
| EN 1992 with MC2010 cv | 0.2082 | 0.155 | 1.32 | 0.118 |

Because the two models are the same except `C_Rck` and `gamma_C` the gain from a reduced model uncertainty can be easily computed as single value:
0.118 / 0.107 = 1.10 

(This is the same as what we would get by only comparing the partial factors if we used the same `C_Rck` value for both models.)

If the two models differ in more than just two parameters then the comparison could be done as the ratio of design values considering all design scenarios (that would be equivalent to the above shown case (special case)). This would lead to a distribution of ratios, we could use the mean of it to indicate the average gain.

What do you think?

**Comment by slobbeat** [comment]
Though I think it's an interesting exercise, I have two reservations:
1. Are we really interested in quantifying the model improvement? I thought there we do this variation to show the impact of using another resistance model (with different model uncertainty) on the partial factor. 
2. If we assume that the shear database contains experiments that are representative for all design applications we have in mind for the shear formula, would your proposal then lead to a different outcome than comparing partial factors? 

Probably, this assumption is not correct, and the measure you propose can correct for a possible misinterpretation that one resistance model is better than the other, while it may only be better fit with the observed data. Is that indeed what you want to indicate?

**Comment by rozsasarpi** [comment]
> Are we really interested in quantifying the model improvement? I thought there we do this variation to show the impact of using another resistance model (with different model uncertainty) on the partial factor.

I only called it model improvement because last week talked about using an alternative model that is more accurate, i.e. has a smaller model uncertainty, but what I present above is not tied to improvement. In my opinion it (or something similar) is needed for a fair model comparison. Ultimately, the partial factor is not telling us much if we also change at least another parameter in the formulas, e.g. `C_Rck`. How would you make the comparisons?

> 2. If we assume that the shear database contains experiments that are representative for all design applications we have in mind for the shear formula, would your proposal then lead to a different outcome than comparing partial factors.

I think the question is not related to weather the experimental data is representative or not. I do not correct this as I do not have information to do so. A comparison of only the partial factors is going to be distorted (in the case that I think we advocate, i.e. also calibrate the `C_Rck` or whatever parameter) by the other parameter that we touch in the formula.

**Comment by slobbeat** [comment]
As discussed during a phone call: 
 - The proposed comparison is indeed relevant to give some interpretation to the outcomes;
 - Since it's not hard to explain, we think it is manageable to add it to the paper and it will not distract the reader from the main message.
 
In conclusion, the proposed comparison will be added.

**Comment by rozsasarpi** [comment]
The required changes are implemented in #20.
